# Generated by Django 4.2.17 on 2025-01-29 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0002_alter_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplybooksapi.genre'),
        ),
    ]
