# Generated by Django 4.2.17 on 2025-01-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0004_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='simplybooksapi.genre'),
        ),
    ]
