# Generated by Django 4.2.17 on 2025-01-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0005_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genres',
            new_name='genre',
        ),
    ]
